#!/bin/bash
mkdir q exe 2> /dev/null
ls memory || dd if=/dev/zero of=memory bs=1024 count=1048576
for e in `ls games/`
do
	name=`echo $e | cut -f1 -d'.'`
	python3 ../compasm/mcasm.py games/$e ./exe/$name.EXE
done
gcc -c ../ozcomp/OzEmu/libs/kbd.c
g++ -o a.out ../ozcomp/OzEmu/main.cpp ../ozcomp/OzEmu/libs/beeper.cpp kbd.o -lc -lncurses -lpthread -lSDL2
mkfs.fat -R 5 memory
sudo mount memory q
sudo cp exe/* q/
sudo umount q
python3 ../compasm/mcasm.py shell.asm mem 62 
python3 collector.py mem memory 
sudo chmod +rwx /dev/input/mice
rm *.o 2> /dev/null
