#!/bin/bash
mkdir q exe 2> /dev/null
ls memory || dd if=/dev/zero of=memory bs=1024 count=1048576
for e in `ls games/`
do
	name=`echo $e | cut -f1 -d'.'`
	python3 ../compasm/mcasm.py games/$e ./exe/$name.EXE
done
gcc -c ../ozcomp/OzEmu/libs/kbd.c; g++ -o a.out ../ozcomp/OzEmu/main.cpp kbd.o -lc -lncurses -lpthread
mkfs.fat -R 3 memory
sudo mount memory q
sudo mkdir q/dir.COM
sudo mkdir q/dirk.COM
sudo mkdir q/DIRECT
sudo touch q/123.COM
sudo touch q/DIRECT/file.COM
sudo touch q/File
sudo touch q/.COM
sudo touch q/qwww.COM
sudo touch q/dsd.COM
sudo cp exe/* q/DIRECT/
sudo cp exe/* q/
sudo umount q
python3 ../compasm/mcasm.py shell.asm mem 62 
python3 collector.py mem memory 
rm *.o 2> /dev/null
sudo stty -F /dev/ttyUSB0 9600
#aplay -q -f cd < pipe & ./a.out
