#!/bin/bash
mkdir q 2> /dev/null
ls memory || dd if=/dev/zero of=memory bs=2048 count=1048576
python3 ../CompAsm/mcasm.py ../OzComp/games/dino_chrome.asm ./exe/DINO.EXE
python3 ../CompAsm/mcasm.py ../OzComp/games/snake.asm ./exe/SNAKE.EXE
g++ -c ~/OzComp/OzEmu/main.cpp && g++ main.o -lsfml-graphics -lsfml-window -lsfml-system -lncurses -lSDL
mkfs.fat -R 3 memory
sudo mount memory q
sudo mkdir q/dir.COM
sudo mkdir q/dirk.COM
sudo mkdir q/DIRECT
sudo touch q/123.COM
sudo touch q/DIRECT/file.COM
sudo touch q/File
sudo touch q/.COM
sudo touch q/qwww.COM
sudo touch q/dsd.COM
sudo cp exe/* q/DIRECT/
sudo cp exe/* q/
sudo umount q
python3 ../CompAsm/mcasm.py shell.asm mem 62 
python3 collector.py mem memory 
./a.out
rm main.o 2> /dev/null
